In [153]:
import pandas as pd
import numpy as np
from pathlib import Path

---------------------------------------------------------------------------------------------------------------------------------------------
### Загрузка данных
---------------------------------------------------------------------------------------------------------------------------------------------

In [324]:
DATA_PATH = Path("../data/raw")

tables = {}
for file in DATA_PATH.glob('*.csv'):
    tables[file.stem] = pd.read_csv(file)

tables.keys()

dict_keys(['olist_sellers_dataset', 'product_category_name_translation', 'olist_orders_dataset', 'olist_order_items_dataset', 'olist_customers_dataset', 'olist_geolocation_dataset', 'olist_order_payments_dataset', 'olist_order_reviews_dataset', 'olist_products_dataset'])

In [326]:
sellers_df = tables['olist_sellers_dataset']
product_category_df = tables['product_category_name_translation']
orders_df = tables['olist_orders_dataset']
order_items_df = tables['olist_order_items_dataset']
customers_df = tables['olist_customers_dataset']
geolocation_df = tables['olist_geolocation_dataset']
order_payments_df = tables['olist_order_payments_dataset']
order_reviews_df = tables['olist_order_reviews_dataset']
products_df = tables['olist_products_dataset']

---------------------------------------------------------------------------------------------------------------------------------------------
### Общая информация о датасетах
---------------------------------------------------------------------------------------------------------------------------------------------

In [328]:
def dataset_info(df, name):
    print('-' * 140)
    print(name)
    print(f'Shape: {df.shape}')
    display(df.head())
    display(df.info(memory_usage='deep'))
    display(df.describe(include="all").T)

for name, df in tables.items():
    dataset_info(df, name)

--------------------------------------------------------------------------------------------------------------------------------------------
olist_sellers_dataset
Shape: (3095, 4)

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
dtypes: int64(1), object(3)
memory usage: 602.2 KB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
seller_id,3095,3095,3442f8959a84dea7ee197c632cb2df15,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_zip_code_prefix,3095.0,NaN,NaN,NaN,32291.059,32713.454,1001.0,7093.5,14940.0,64552.5,99730.0
seller_city,3095,611,sao paulo,694,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_state,3095,23,SP,1849,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------------------------------------------------------------------
product_category_name_translation
Shape: (71, 2)

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 9.2 KB

None

                              count unique            top freq
product_category_name            71     71   beleza_saude    1
product_category_name_english    71     71  health_beauty    1

--------------------------------------------------------------------------------------------------------------------------------------------
olist_orders_dataset
Shape: (99441, 8)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 52.9 MB

None

,count,unique,top,freq
order_id,99441,99441,e481f51cbdc54678b7cc49136f2d6af7,1
customer_id,99441,99441,9ef432eb6251297304e76186b10a928d,1
order_status,99441,8,delivered,96478
order_purchase_timestamp,99441,98875,2018-04-11 10:48:14,3
order_approved_at,99281,90733,2018-02-27 04:31:10,9
order_delivered_carrier_date,97658,81018,2018-05-09 15:48:00,47
order_delivered_customer_date,96476,95664,2018-05-08 23:38:46,3
order_estimated_delivery_date,99441,459,2017-12-20 00:00:00,522

--------------------------------------------------------------------------------------------------------------------------------------------
olist_order_items_dataset
Shape: (112650, 7)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: float64(2), int64(1), object(4)
memory usage: 36.0 MB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,112650,98666,8272b63d03f5f79c56e9e4120aec44ef,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_item_id,112650.0,NaN,NaN,NaN,1.198,0.705,1.0,1.0,1.0,1.0,21.0
product_id,112650,32951,aca2eb7d00ea1a7b8ebd4e68314663af,527,NaN,NaN,NaN,NaN,NaN,NaN,NaN
seller_id,112650,3095,6560211a19b47992c3666cc44a7e94c0,2033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
shipping_limit_date,112650,93318,2017-07-21 18:25:23,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN
price,112650.0,NaN,NaN,NaN,120.654,183.634,0.85,39.9,74.99,134.9,6735.0
freight_value,112650.0,NaN,NaN,NaN,19.99,15.806,0.0,13.08,16.26,21.15,409.68

--------------------------------------------------------------------------------------------------------------------------------------------
olist_customers_dataset
Shape: (99441, 5)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
dtypes: int64(1), object(4)
memory usage: 26.6 MB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customer_id,99441,99441,06b8999e2fba1a1fbc88172c00ba8bc7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_unique_id,99441,96096,8d50f5eadf50201ccdcedfb9e2ac8455,17,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_zip_code_prefix,99441.0,NaN,NaN,NaN,35137.475,29797.939,1003.0,11347.0,24416.0,58900.0,99990.0
customer_city,99441,4119,sao paulo,15540,NaN,NaN,NaN,NaN,NaN,NaN,NaN
customer_state,99441,27,SP,41746,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------------------------------------------------------------------
olist_geolocation_dataset
Shape: (1000163, 5)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.546,-46.639,sao paulo,SP
1,1046,-23.546,-46.645,sao paulo,SP
2,1046,-23.546,-46.643,sao paulo,SP
3,1041,-23.544,-46.639,sao paulo,SP
4,1035,-23.542,-46.642,sao paulo,SP

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 129.4 MB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
geolocation_zip_code_prefix,1000163.0,NaN,NaN,NaN,36574.166,30549.336,1001.0,11075.0,26530.0,63504.0,99990.0
geolocation_lat,1000163.0,NaN,NaN,NaN,-21.176,5.716,-36.605,-23.604,-22.919,-19.98,45.066
geolocation_lng,1000163.0,NaN,NaN,NaN,-46.391,4.27,-101.467,-48.573,-46.638,-43.768,121.105
geolocation_city,1000163,8011,sao paulo,135800,NaN,NaN,NaN,NaN,NaN,NaN,NaN
geolocation_state,1000163,27,SP,404268,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------------------------------------------------------------------
olist_order_payments_dataset
Shape: (103886, 5)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: float64(1), int64(2), object(2)
memory usage: 16.2 MB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
order_id,103886,99440,fa65dad1b0e818e3ccc5cb0e39231352,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_sequential,103886.0,NaN,NaN,NaN,1.093,0.707,1.0,1.0,1.0,1.0,29.0
payment_type,103886,5,credit_card,76795,NaN,NaN,NaN,NaN,NaN,NaN,NaN
payment_installments,103886.0,NaN,NaN,NaN,2.853,2.687,0.0,1.0,1.0,4.0,24.0
payment_value,103886.0,NaN,NaN,NaN,154.1,217.494,0.0,56.79,100.0,171.838,13664.08

--------------------------------------------------------------------------------------------------------------------------------------------
olist_order_reviews_dataset
Shape: (99224, 7)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  object
 4   review_comment_message   40977 non-null  object
 5   review_creation_date     99224 non-null  object
 6   review_answer_timestamp  99224 non-null  object
dtypes: int64(1), object(6)
memory usage: 39.1 MB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
review_id,99224,98410,7b606b0d57b078384f0b58eac1d41d78,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
order_id,99224,98673,c88b1d1b157a9999ce368f218a407141,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_score,99224.0,NaN,NaN,NaN,4.086,1.348,1.0,4.0,5.0,5.0,5.0
review_comment_title,11568,4527,Recomendo,423,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_comment_message,40977,36159,Muito bom,230,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_creation_date,99224,636,2017-12-19 00:00:00,463,NaN,NaN,NaN,NaN,NaN,NaN,NaN
review_answer_timestamp,99224,98248,2017-06-15 23:21:05,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN

--------------------------------------------------------------------------------------------------------------------------------------------
olist_products_dataset
Shape: (32951, 9)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: float64(7), object(2)
memory usage: 6.3 MB

None

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
product_id,32951,32951,1e9e8ef04dbcff4541ed26657ea517e5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_category_name,32341,73,cama_mesa_banho,3029,NaN,NaN,NaN,NaN,NaN,NaN,NaN
product_name_lenght,32341.0,NaN,NaN,NaN,48.477,10.246,5.0,42.0,51.0,57.0,76.0
product_description_lenght,32341.0,NaN,NaN,NaN,771.495,635.115,4.0,339.0,595.0,972.0,3992.0
product_photos_qty,32341.0,NaN,NaN,NaN,2.189,1.737,1.0,1.0,1.0,3.0,20.0
product_weight_g,32949.0,NaN,NaN,NaN,2276.472,4282.039,0.0,300.0,700.0,1900.0,40425.0
product_length_cm,32949.0,NaN,NaN,NaN,30.815,16.914,7.0,18.0,25.0,38.0,105.0
product_height_cm,32949.0,NaN,NaN,NaN,16.938,13.638,2.0,8.0,13.0,21.0,105.0
product_width_cm,32949.0,NaN,NaN,NaN,23.197,12.079,6.0,15.0,20.0,30.0,118.0

---------------------------------------------------------------------------------------------------------------------------------------------
### Проверка пропущенных значений
---------------------------------------------------------------------------------------------------------------------------------------------

In [336]:
def missing_info(df, name):
    print(f'Пропущенные значения в таблице {name}: ')
    df_missing = df.isnull().sum().to_frame("missing_count")
    df_missing['missing_percent'] = (df_missing['missing_count'] / len(df) * 100).round(2)
    display(df_missing)
    print()

for name, df in tables.items():
    missing_info(df, name)

Пропущенные значения в таблице olist_sellers_dataset:

                        missing_count  missing_percent
seller_id                           0              0.0
seller_zip_code_prefix              0              0.0
seller_city                         0              0.0
seller_state                        0              0.0

Пропущенные значения в таблице product_category_name_translation:

                               missing_count  missing_percent
product_category_name                      0              0.0
product_category_name_english              0              0.0

Пропущенные значения в таблице olist_orders_dataset:

                               missing_count  missing_percent
order_id                                   0             0.00
customer_id                                0             0.00
order_status                               0             0.00
order_purchase_timestamp                   0             0.00
order_approved_at                        160             0.16
order_delivered_carrier_date            1783             1.79
order_delivered_customer_date           2965             2.98
order_estimated_delivery_date              0             0.00

Пропущенные значения в таблице olist_order_items_dataset:

                     missing_count  missing_percent
order_id                         0              0.0
order_item_id                    0              0.0
product_id                       0              0.0
seller_id                        0              0.0
shipping_limit_date              0              0.0
price                            0              0.0
freight_value                    0              0.0

Пропущенные значения в таблице olist_customers_dataset:

                          missing_count  missing_percent
customer_id                           0              0.0
customer_unique_id                    0              0.0
customer_zip_code_prefix              0              0.0
customer_city                         0              0.0
customer_state                        0              0.0

Пропущенные значения в таблице olist_geolocation_dataset:

                             missing_count  missing_percent
geolocation_zip_code_prefix              0              0.0
geolocation_lat                          0              0.0
geolocation_lng                          0              0.0
geolocation_city                         0              0.0
geolocation_state                        0              0.0

Пропущенные значения в таблице olist_order_payments_dataset:

                      missing_count  missing_percent
order_id                          0              0.0
payment_sequential                0              0.0
payment_type                      0              0.0
payment_installments              0              0.0
payment_value                     0              0.0

Пропущенные значения в таблице olist_order_reviews_dataset:

                         missing_count  missing_percent
review_id                            0             0.00
order_id                             0             0.00
review_score                         0             0.00
review_comment_title             87656            88.34
review_comment_message           58247            58.70
review_creation_date                 0             0.00
review_answer_timestamp              0             0.00

Пропущенные значения в таблице olist_products_dataset:

                            missing_count  missing_percent
product_id                              0             0.00
product_category_name                 610             1.85
product_name_lenght                   610             1.85
product_description_lenght            610             1.85
product_photos_qty                    610             1.85
product_weight_g                        2             0.01
product_length_cm                       2             0.01
product_height_cm                       2             0.01
product_width_cm                        2             0.01

In [366]:
display(orders_df[
    orders_df["order_approved_at"].isna()
][["order_status"]].value_counts())
print()
display(orders_df[
    orders_df["order_delivered_carrier_date"].isna()
][["order_status"]].value_counts())
print()
display(orders_df[
    orders_df["order_delivered_customer_date"].isna()
][["order_status"]].value_counts())
print()
display(order_reviews_df[
    order_reviews_df["review_comment_message"].isna()
][["review_score"]].value_counts())

order_status
canceled        141
delivered        14
created           5
Name: count, dtype: int64

order_status
unavailable     609
canceled        550
invoiced        314
processing      301
created           5
approved          2
delivered         2
Name: count, dtype: int64

order_status
shipped         1107
canceled         619
unavailable      609
invoiced         314
processing       301
delivered          8
created            5
approved           2
Name: count, dtype: int64

review_score
5               36774
4               13166
3                4622
1                2679
2                1006
Name: count, dtype: int64

---------------------------------------------------------------------------------------------------------------------------------------------
### Проверка дубликатов во всей таблице и по первичным ключам
---------------------------------------------------------------------------------------------------------------------------------------------

In [249]:
print('Количество дубликатов в каждой таблице:')
for name, df in tables.items():
    print(f'{name}: {df.duplicated().sum()}')

Количество дубликатов в каждой таблице:
olist_sellers_dataset: 0
product_category_name_translation: 0
olist_orders_dataset: 0
olist_order_items_dataset: 0
olist_customers_dataset: 0
olist_geolocation_dataset: 261831
olist_order_payments_dataset: 0
olist_order_reviews_dataset: 0
olist_products_dataset: 0

In [330]:
print('Количество дубликатов первичного ключа в каждой таблице:')
print(f'sellers_df: {sellers_df.duplicated(['seller_id']).sum()}')
print(f'product_category_df: {product_category_df.duplicated(['product_category_name']).sum()}')
print(f'orders_df: {orders_df.duplicated(['order_id']).sum()}')
print(f'order_items_df: {order_items_df.duplicated(subset=['order_id', 'order_item_id']).sum()}')
print(f'customers_df: {customers_df.duplicated(['customer_id']).sum()}')
print(f'order_payments_df: {order_payments_df.duplicated(subset=['order_id', 'payment_sequential']).sum()}') 
print(f'order_reviews_df: {order_reviews_df.duplicated(subset=['review_id', 'order_id']).sum()}')
print(f'products_df: {products_df.duplicated(['product_id']).sum()}')
print('\nКоличество дубликатов комбинации координат и ZIP-кода, т.к. PK отсутствует:')
print(f'geolocation_df: {geolocation_df.duplicated(['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng']).sum()}')

Количество дубликатов первичного ключа в каждой таблице:
sellers_df: 0
product_category_df: 0
orders_df: 0
order_items_df: 0
customers_df: 0
order_payments_df: 0
order_reviews_df: 0
products_df: 0

Количество дубликатов комбинации координат и ZIP-кода, т.к. PK отсутствует:
geolocation_df: 280009

---------------------------------------------------------------------------------------------------------------------------------------------
### Проверка типов данных
---------------------------------------------------------------------------------------------------------------------------------------------

In [332]:
print('Типы данных каждой таблицы:')
for name, df in tables.items():
    print(f'\n{name}:')
    display(df.dtypes)

Типы данных каждой таблицы:

olist_sellers_dataset:

seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

product_category_name_translation:

product_category_name            object
product_category_name_english    object
dtype: object

olist_orders_dataset:

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

olist_order_items_dataset:

order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

olist_customers_dataset:

customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

olist_geolocation_dataset:

geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

olist_order_payments_dataset:

order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

olist_order_reviews_dataset:

review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

olist_products_dataset:

product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

---------------------------------------------------------------------------------------------------------------------------------------------
### Проверка логики дат
---------------------------------------------------------------------------------------------------------------------------------------------

In [355]:
reviews_date_df = order_reviews_df[['order_id','review_creation_date','review_answer_timestamp']]
merge_orders_reviews = orders_df.merge(reviews_date_df, how='left', on='order_id')

In [374]:
def check_anomaly(df, condition, message):
    mask = df.eval(condition)
    count = mask.sum()
    print(f"{message}: {count}")
    if count > 0:
        display(df[mask].head())

check_anomaly(
    orders_df,
    'order_delivered_customer_date < order_purchase_timestamp',
    'Доставка раньше оформления'
)

check_anomaly(
    orders_df,
    'order_approved_at < order_purchase_timestamp',
    'Подтверждение раньше оформления'
)

check_anomaly(
    orders_df,
    'order_delivered_customer_date < order_delivered_carrier_date',
    'Передача в доставку позже доставки заказа'
)

check_anomaly(
    orders_df,
    'order_delivered_carrier_date < order_purchase_timestamp',
    'Передача в доставку раньше оформления'
)

check_anomaly(
    order_reviews_df,
    'review_answer_timestamp < review_creation_date',
    'Ответ на отзыв раньше, чем отзыв был оставлен'
)

check_anomaly(
    merge_orders_reviews,
    'review_creation_date < order_purchase_timestamp',
    'Отзыв раньше заказа'
)

Доставка раньше оформления: 0
Подтверждение раньше оформления: 0
Передача в доставку позже доставки заказа: 23

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,5f50465da00b7fed5dd1239f4ecf6e2c,delivered,2017-07-20 11:20:52,2017-07-21 06:43:14,2017-07-28 16:57:58,2017-07-25 19:32:56,2017-08-14 00:00:00
9553,383aa8b2724fe452d9ccd9934a8c628b,b1cb2f9d7a19480f3749e248db14d58f,delivered,2017-07-02 20:58:43,2017-07-02 21:10:20,2017-07-07 17:22:41,2017-07-06 14:27:51,2017-07-21 00:00:00
13487,cb1134f9010d242e9515ad1c78ec0c39,2fd33ac77677bd214b1882868317eeed,delivered,2017-07-16 12:35:34,2017-07-18 06:03:50,2017-07-20 19:22:02,2017-07-19 14:13:28,2017-08-08 00:00:00
14474,dceb62e8fa94b46006c9554fed743df0,2721900eb4e0f1cc2c836dd7bc1b1e11,delivered,2017-07-20 20:58:05,2017-07-22 11:45:11,2017-08-01 18:23:30,2017-07-26 18:09:10,2017-08-11 00:00:00
19268,5f9d46795c3126674e52becb3a1a517f,79287bcaafdde5c793b996fc40bb7d9f,delivered,2017-07-18 11:48:20,2017-07-18 12:03:29,2017-07-20 23:03:42,2017-07-20 18:52:41,2017-07-31 00:00:00

Передача в доставку раньше оформления: 166

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
615,b9afddbdcfadc9a87b41a83271c3e888,85c6af75161b8b2b1af98e82b5a6a5a5,delivered,2018-08-16 13:50:48,2018-08-16 14:05:13,2018-08-16 13:27:00,2018-08-24 14:58:37,2018-09-04 00:00:00
1111,ad133696906f6a78826daa0911b7daec,e6f5b234bb0d847f10eebd70130c5d49,delivered,2018-06-15 15:41:22,2018-06-15 16:19:23,2018-06-15 14:52:00,2018-06-22 18:09:37,2018-07-18 00:00:00
1329,74e033208dc13a7b8127eb8e73d09b76,72fcbb1145f2889eddcba6d6c1d6c090,delivered,2018-05-02 10:48:44,2018-05-02 11:13:45,2018-05-02 09:49:00,2018-05-07 23:06:36,2018-05-29 00:00:00
1372,a6b58794fd2ba533359a76c08df576e3,ccd8e3459ad58ae538c9d2cf35532ba4,delivered,2018-05-14 15:18:23,2018-05-14 15:33:35,2018-05-14 13:46:00,2018-05-19 19:33:32,2018-06-08 00:00:00
1864,5792e0b1c8c8a2bf53af468c9a422c88,5c427f06e7fcf902e309743516e2c580,delivered,2018-07-26 13:25:14,2018-07-26 13:35:14,2018-07-26 12:42:00,2018-07-30 14:45:02,2018-08-09 00:00:00

Ответ на отзыв раньше, чем отзыв был оставлен: 0
Отзыв раньше заказа: 74

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,review_creation_date,review_answer_timestamp
1136,00b1cb0320190ca0daa2c88b35206009,3532ba38a3fd242259a514ac2b6ae6b6,canceled,2018-08-28 15:26:39,NaN,NaN,NaN,2018-09-12 00:00:00,2018-08-28 00:00:00,2018-08-28 18:25:55
1811,ed3efbd3a87bea76c2812c66a0b32219,191984a8ba4cbb2145acb4fe35b69664,canceled,2018-09-20 13:54:16,NaN,NaN,NaN,2018-10-17 00:00:00,2018-07-28 00:00:00,2018-07-30 11:06:16
2039,8d4c637f1accf7a88a4555f02741e606,b1dd715db389a2077f43174e7a675d07,canceled,2018-08-29 16:27:49,NaN,NaN,NaN,2018-09-13 00:00:00,2018-08-26 00:00:00,2018-08-26 20:21:38
3109,5290c34bd38a8a095b885f13958db1e1,92af427e290117f39d9ff908566072e0,canceled,2018-08-21 10:25:18,NaN,NaN,NaN,2018-09-06 00:00:00,2018-08-18 00:00:00,2018-08-21 00:47:13
3701,03310aa823a66056268a3bab36e827fb,25dbbf0c477fd4ae0880aaffbb12e8b3,canceled,2018-08-07 16:33:59,NaN,NaN,NaN,2018-09-04 00:00:00,2018-08-03 00:00:00,2018-08-06 00:09:52

---------------------------------------------------------------------------------------------------------------------------------------------
## Проверка выхода за границы допустимого диапазона финансовых показателей
---------------------------------------------------------------------------------------------------------------------------------------------

In [467]:
finance_columnas = {
    'price': order_items_df,
    'freight_value': order_items_df,
    'payment_value': order_payments_df
}

def financail_features(df, column_name): 
    if len(df[df[column_name] < 0]) > 0:
        display(df[df[column_name] < 0])
        print()
    else:
        print(f'Выход за границы допустимого диапазона в колонке {column_name} не обнаружено')

for column_name, df in finance_columnas.items():
    financail_features(df, column_name)

Выход за границы допустимого диапазона в колонке price не обнаружено
Выход за границы допустимого диапазона в колонке freight_value не обнаружено
Выход за границы допустимого диапазона в колонке payment_value не обнаружено

---------------------------------------------------------------------------------------------------------------------------------------------
### Проверка категориальных признаков
---------------------------------------------------------------------------------------------------------------------------------------------

In [442]:
categorical_columnas = {
    'order_status': orders_df,
    'payment_type': order_payments_df,
    'review_score': order_reviews_df,
}

def categorical_features(df, column_name): 
    display(df[column_name].value_counts())
    print()

for column_name, df in categorical_columnas.items():
    categorical_features(df, column_name)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

---------------------------------------------------------------------------------------------------------------------------------------------
## Вывод по результатам Data Profiling

В рамках этапа первичного профилирования данных был выполнен комплексный анализ качества, структуры и согласованности датасетов, включающий проверку схемы данных, полноты, целостности, корректности типов и бизнес-логики.

### Выполненные проверки

- проанализирована структура всех таблиц и соответствие данных ожидаемой схеме;
- валидированы типы данных, определены поля, требующие преобразования (в первую очередь временные атрибуты);
- выполнен анализ пропусков с классификацией их природы (технические, бизнес-обусловленные, ожидаемые);
- проверена уникальность и корректность первичных ключей;
- выполнен анализ дубликатов на уровне записей и ключевых полей;
- проведена валидация бизнес-логики временных последовательностей;
- проверены распределения финансовых показателей и базовые аномалии значений;
- проанализированы категориальные признаки и их распределения.

---------------------------------------------------------------------------------------------------------------------------------------------

### Основные наблюдения

- полные дубликаты выявлены только в таблице `geolocation`, что связано с особенностями хранения координат на уровне ZIP-кодов, а не с ошибками генерации данных;
- нарушения уникальности первичных ключей не выявлены (за исключением `geolocation`, где первичный ключ отсутствует по природе датасета);
- пропуски в данных преимущественно ожидаемы и объясняются жизненным циклом заказа (этапы обработки, доставки, отмены);
- все временные поля загружены в формате `object` и требуют приведения к типу `datetime` для корректного анализа;
- критических нарушений логики временных последовательностей не выявлено, зафиксированные аномалии носят единичный характер и не влияют на общую консистентность данных;
- аномалий в категориальных распределениях не обнаружено.

---------------------------------------------------------------------------------------------------------------------------------------------

### Анализ финансовых показателей и выбросов

- отрицательные значения в `price`, `freight_value` и `payment_value` отсутствуют;
- значения финансовых метрик находятся в допустимых бизнес-диапазонах;
- распределения показателей имеют выраженную правостороннюю асимметрию, что характерно для e-commerce данных (наличие длинного хвоста дорогих заказов);
- наблюдаются потенциальные выбросы в верхних квантилях (особенно по `price` и `payment_value`), однако они интерпретируются как валидные бизнес-наблюдения, а не ошибки данных.